[build]
  install = "npm ci --include=optional"
  command = "npm run build --workspace=web"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=optional"
  NPM_CONFIG_PRODUCTION = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
